57 add p rocess images
ospin-web-dev/nexus pull request #10
Opened 2021-07-15 10:45 UTC by FelixMZ2018

2021-07-15 15:16 UTC, FelixMZ2018 commented on src/process/functionality/image/index.js
> + */
```suggestion
```

2021-07-16 08:10 UTC, DanielSeehausen commented on .eslintrc.js
> +  extends: [
🙏

2021-07-16 08:12 UTC, DanielSeehausen commented on src/process/functionality/image/create.js
> + * requires the image to be encoded in base64
perhaps duplicate description re: base 64

2021-07-16 08:14 UTC, DanielSeehausen commented on src/process/functionality/image/create.js
> + * @param {string} ProcessId @param {string} FunctionalityID @param {object} Body
```suggestion
 * @param {string} ProcessId @param {string} FunctionalityId @param {object} Body
```

(or big D on processId)

2021-07-16 08:30 UTC, DanielSeehausen reviewed
Could we add this to the project if we are to start using jsdoc?
Once installed, the plugin might need to be added to the eslint config file

https://eslint.org/docs/rules/valid-jsdoc

2021-07-16 08:49 UTC, DanielSeehausen requested changes
looks great to me! 

only blocking changes are to 
- add jsdoc linting
- update test file path to match src file path

2021-07-16 11:23 UTC, FelixMZ2018 commented
> Could we add this to the project if we are to start using jsdoc?
> Once installed, the plugin might need to be added to the eslint config file
> 
> https://eslint.org/docs/rules/valid-jsdoc

I added https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-installation since the eslint version is end of life and its the recommended replacement



> looks great to me!
> 
> only blocking changes are to
> 
> * add jsdoc linting
> * update test file path to match src file path

done and done

2021-07-19 10:42 UTC, DanielSeehausen approved these changes
gopher it!

2021-07-19 13:49 UTC, merged