feat: add support for the new endpoint to sync process port assigment with its functionality graph
ospin-web-dev/nexus pull request #113
Opened 2022-09-29 14:40 UTC by FelixMZ2018

feat: added sync process port
feat: added update ports on device

2022-09-29 15:22 UTC, FelixMZ2018 commented on src/device/functionalityGraph/ports/index.js
> +
```suggestion

/**
 * @namespace nexus.device.functionalityGraph.ports
 */
```

2022-09-29 15:22 UTC, FelixMZ2018 commented on src/process/physicalMapping/index.js
> +
```suggestion

/**
 * @namespace nexus.process.physicalMapping
 */
```

2022-09-30 07:34 UTC, vdiezel commented on test/src/device/functionalityGraph/ports/update.test.js
> +})
We have an even shorter abstraction: the `testHTTPEndpoint` test helper. Applies to both tests.

2022-09-30 07:35 UTC, vdiezel requested changes
Solid. 
Just for the test suites we have a helper function that reduces the boilerplate even further.

2022-10-06 09:10 UTC, vdiezel requested changes
The test files can be cleaned up even further :)

check the licence add test.

2022-10-07 08:23 UTC, vdiezel approved these changes

2022-10-07 10:51 UTC, merged