feat: 139 post /users/userid/UI config
ospin-web-dev/nexus pull request #141
Opened 2023-05-11 11:02 UTC by cairesana

- closes #139

2023-05-15 07:38 UTC, lev-leontyev-ospin submitted a review, later dismissed

2023-05-15 07:38 UTC, lev-leontyev-ospin commented on test/src/uIConfig/userUIConfig/post.test.js
> +  it('calls amplify\'s API.get method', async () => {
name doesn't match the test itself

2023-05-15 07:39 UTC, lev-leontyev-ospin commented
One non-blocking point.

2023-05-15 07:58 UTC, cairesana commented
@Lev, I have updated the name, thanks for catching this

2023-05-15 08:22 UTC, FelixMZ2018 commented on src/uIConfig/userUIConfig/post.js
> + * @returns {Promise<ApiResponse>}
this definition would mean the function is called like this

```
fn ({userId}) 
```

but thats not what we want but instead we have 2 params , the first beeing a string and the other one beeing an object (but we dont define the keys of the object here( so no params.something, simple params would be enough) 

```
 * @param {object} params
 * @param {string} params.userId
 ```
is a single function param, 

```
 * @param {object} params
 * @param {string} params2
 ```
 means the function has 2 params

2023-05-15 08:23 UTC, FelixMZ2018 requested changes
there is a small mistake in the docs

2023-05-15 13:04 UTC, cairesana commented on src/uIConfig/userUIConfig/post.js
> + * @returns {Promise<ApiResponse>}
done

2023-05-17 13:01 UTC, FelixMZ2018 submitted a review, later dismissed

2023-06-05 11:01 UTC, vdiezel approved these changes

2023-06-05 11:51 UTC, merged