re-send-confirmation
ospin-web-dev/nexus pull request #163
Opened 2023-09-01 13:44 UTC by FelixMZ2018

2023-09-06 09:54 UTC, lev-leontyev-ospin requested changes

2023-09-06 09:54 UTC, lev-leontyev-ospin commented on test/src/auth/resendConfirmationCode.test.js
> +        status: 200,
why no just 
expect.objectContaining(res) ?

2023-09-06 14:24 UTC, FelixMZ2018 commented on test/src/auth/resendConfirmationCode.test.js
> +        status: 200,
can also remove the object containing 

fixed

2023-09-07 08:05 UTC, lev-leontyev-ospin approved these changes

2023-09-07 08:48 UTC, merged